//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOTONSAP.consultas {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.efactura.isaltda.py/", ConfigurationName="consultas.Consultas")]
    public interface Consultas {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación consultaRuc no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BOTONSAP.consultas.consultaRucResponse consultaRuc(BOTONSAP.consultas.consultaRucRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BOTONSAP.consultas.consultaRucResponse> consultaRucAsync(BOTONSAP.consultas.consultaRucRequest1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación consultaInutilizacion no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BOTONSAP.consultas.consultaInutilizacionResponse1 consultaInutilizacion(BOTONSAP.consultas.consultaInutilizacionRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BOTONSAP.consultas.consultaInutilizacionResponse1> consultaInutilizacionAsync(BOTONSAP.consultas.consultaInutilizacionRequest1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación consultaDEPorCiclo no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BOTONSAP.consultas.consultaDEPorCicloResponse1 consultaDEPorCiclo(BOTONSAP.consultas.consultaDEPorCicloRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BOTONSAP.consultas.consultaDEPorCicloResponse1> consultaDEPorCicloAsync(BOTONSAP.consultas.consultaDEPorCicloRequest1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación consultaPorCDC no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BOTONSAP.consultas.consultaPorCDCResponse1 consultaPorCDC(BOTONSAP.consultas.consultaPorCDCRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BOTONSAP.consultas.consultaPorCDCResponse1> consultaPorCDCAsync(BOTONSAP.consultas.consultaPorCDCRequest1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación consultaRecibido no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BOTONSAP.consultas.consultaRecibidoResponse1 consultaRecibido(BOTONSAP.consultas.consultaRecibidoRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BOTONSAP.consultas.consultaRecibidoResponse1> consultaRecibidoAsync(BOTONSAP.consultas.consultaRecibidoRequest1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación consulta no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BOTONSAP.consultas.consultaResponse1 consulta(BOTONSAP.consultas.consultaRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BOTONSAP.consultas.consultaResponse1> consultaAsync(BOTONSAP.consultas.consultaRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.efactura.isaltda.py/")]
    public partial class consultaRucRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] rucField;
        
        private bool retornarRespuestaOriginalField;
        
        private bool retornarRespuestaOriginalFieldSpecified;
        
        private string apikeyField;
        
        private string usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ruc", Order=0)]
        public string[] ruc {
            get {
                return this.rucField;
            }
            set {
                this.rucField = value;
                this.RaisePropertyChanged("ruc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool retornarRespuestaOriginal {
            get {
                return this.retornarRespuestaOriginalField;
            }
            set {
                this.retornarRespuestaOriginalField = value;
                this.RaisePropertyChanged("retornarRespuestaOriginal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool retornarRespuestaOriginalSpecified {
            get {
                return this.retornarRespuestaOriginalFieldSpecified;
            }
            set {
                this.retornarRespuestaOriginalFieldSpecified = value;
                this.RaisePropertyChanged("retornarRespuestaOriginalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string apikey {
            get {
                return this.apikeyField;
            }
            set {
                this.apikeyField = value;
                this.RaisePropertyChanged("apikey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.efactura.isaltda.py/")]
    public partial class numeroTipoDocumento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroField;
        
        private string numeroSerieField;
        
        private string tipoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string numeroSerie {
            get {
                return this.numeroSerieField;
            }
            set {
                this.numeroSerieField = value;
                this.RaisePropertyChanged("numeroSerie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=2)]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.efactura.isaltda.py/")]
    public partial class datosPaginacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string paginaField;
        
        private string cantidadPaginasField;
        
        private string cantidadRegistrosPorPaginaField;
        
        private long cantidadTotalRegistrosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string pagina {
            get {
                return this.paginaField;
            }
            set {
                this.paginaField = value;
                this.RaisePropertyChanged("pagina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string cantidadPaginas {
            get {
                return this.cantidadPaginasField;
            }
            set {
                this.cantidadPaginasField = value;
                this.RaisePropertyChanged("cantidadPaginas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=2)]
        public string cantidadRegistrosPorPagina {
            get {
                return this.cantidadRegistrosPorPaginaField;
            }
            set {
                this.cantidadRegistrosPorPaginaField = value;
                this.RaisePropertyChanged("cantidadRegistrosPorPagina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long cantidadTotalRegistros {
            get {
                return this.cantidadTotalRegistrosField;
            }
            set {
                this.cantidadTotalRegistrosField = value;
                this.RaisePropertyChanged("cantidadTotalRegistros");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.efactura.isaltda.py/")]
    public partial class totales : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long totalDEField;
        
        private long totalIngresadoField;
        
        private long totalAprobadoField;
        
        private long totalAprobadoObsField;
        
        private long totalRechazadoField;
        
        private long totalCanceladoField;
        
        private long totalInutilizadoField;
        
        private long totalReingresadoField;
        
        private long totalRechazadoReingresadoField;
        
        private long totalRechazadoInutilizadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long totalDE {
            get {
                return this.totalDEField;
            }
            set {
                this.totalDEField = value;
                this.RaisePropertyChanged("totalDE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long totalIngresado {
            get {
                return this.totalIngresadoField;
            }
            set {
                this.totalIngresadoField = value;
                this.RaisePropertyChanged("totalIngresado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long totalAprobado {
            get {
                return this.totalAprobadoField;
            }
            set {
                this.totalAprobadoField = value;
                this.RaisePropertyChanged("totalAprobado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long totalAprobadoObs {
            get {
                return this.totalAprobadoObsField;
            }
            set {
                this.totalAprobadoObsField = value;
                this.RaisePropertyChanged("totalAprobadoObs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long totalRechazado {
            get {
                return this.totalRechazadoField;
            }
            set {
                this.totalRechazadoField = value;
                this.RaisePropertyChanged("totalRechazado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long totalCancelado {
            get {
                return this.totalCanceladoField;
            }
            set {
                this.totalCanceladoField = value;
                this.RaisePropertyChanged("totalCancelado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long totalInutilizado {
            get {
                return this.totalInutilizadoField;
            }
            set {
                this.totalInutilizadoField = value;
                this.RaisePropertyChanged("totalInutilizado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public long totalReingresado {
            get {
                return this.totalReingresadoField;
            }
            set {
                this.totalReingresadoField = value;
                this.RaisePropertyChanged("totalReingresado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public long totalRechazadoReingresado {
            get {
                return this.totalRechazadoReingresadoField;
            }
            set {
                this.totalRechazadoReingresadoField = value;
                this.RaisePropertyChanged("totalRechazadoReingresado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public long totalRechazadoInutilizado {
            get {
                return this.totalRechazadoInutilizadoField;
            }
            set {
                this.totalRechazadoInutilizadoField = value;
                this.RaisePropertyChanged("totalRechazadoInutilizado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.efactura.isaltda.py/")]
    public partial class documentoError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.efactura.isaltda.py/")]
    public partial class documento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string cdcField;
        
        private long numeroField;
        
        private bool numeroFieldSpecified;
        
        private string tipoDocumentoField;
        
        private long timbradoField;
        
        private bool timbradoFieldSpecified;
        
        private string establecimientoField;
        
        private string puntoExpedicionField;
        
        private string numeroSerieField;
        
        private System.DateTime fechaIngresoField;
        
        private bool fechaIngresoFieldSpecified;
        
        private System.DateTime fechaEmisionField;
        
        private bool fechaEmisionFieldSpecified;
        
        private string estadoField;
        
        private string estadoEnvioField;
        
        private string estadoAnulacionField;
        
        private string secuenciaField;
        
        private byte[] kuDEField;
        
        private byte[] xmlFirmadoField;
        
        private documentoError[] documentoErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string cdc {
            get {
                return this.cdcField;
            }
            set {
                this.cdcField = value;
                this.RaisePropertyChanged("cdc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroSpecified {
            get {
                return this.numeroFieldSpecified;
            }
            set {
                this.numeroFieldSpecified = value;
                this.RaisePropertyChanged("numeroSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=3)]
        public string tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("tipoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long timbrado {
            get {
                return this.timbradoField;
            }
            set {
                this.timbradoField = value;
                this.RaisePropertyChanged("timbrado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timbradoSpecified {
            get {
                return this.timbradoFieldSpecified;
            }
            set {
                this.timbradoFieldSpecified = value;
                this.RaisePropertyChanged("timbradoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=5)]
        public string establecimiento {
            get {
                return this.establecimientoField;
            }
            set {
                this.establecimientoField = value;
                this.RaisePropertyChanged("establecimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=6)]
        public string puntoExpedicion {
            get {
                return this.puntoExpedicionField;
            }
            set {
                this.puntoExpedicionField = value;
                this.RaisePropertyChanged("puntoExpedicion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string numeroSerie {
            get {
                return this.numeroSerieField;
            }
            set {
                this.numeroSerieField = value;
                this.RaisePropertyChanged("numeroSerie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime fechaIngreso {
            get {
                return this.fechaIngresoField;
            }
            set {
                this.fechaIngresoField = value;
                this.RaisePropertyChanged("fechaIngreso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaIngresoSpecified {
            get {
                return this.fechaIngresoFieldSpecified;
            }
            set {
                this.fechaIngresoFieldSpecified = value;
                this.RaisePropertyChanged("fechaIngresoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.DateTime fechaEmision {
            get {
                return this.fechaEmisionField;
            }
            set {
                this.fechaEmisionField = value;
                this.RaisePropertyChanged("fechaEmision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaEmisionSpecified {
            get {
                return this.fechaEmisionFieldSpecified;
            }
            set {
                this.fechaEmisionFieldSpecified = value;
                this.RaisePropertyChanged("fechaEmisionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string estadoEnvio {
            get {
                return this.estadoEnvioField;
            }
            set {
                this.estadoEnvioField = value;
                this.RaisePropertyChanged("estadoEnvio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string estadoAnulacion {
            get {
                return this.estadoAnulacionField;
            }
            set {
                this.estadoAnulacionField = value;
                this.RaisePropertyChanged("estadoAnulacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=13)]
        public string secuencia {
            get {
                return this.secuenciaField;
            }
            set {
                this.secuenciaField = value;
                this.RaisePropertyChanged("secuencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=14)]
        public byte[] kuDE {
            get {
                return this.kuDEField;
            }
            set {
                this.kuDEField = value;
                this.RaisePropertyChanged("kuDE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=15)]
        public byte[] xmlFirmado {
            get {
                return this.xmlFirmadoField;
            }
            set {
                this.xmlFirmadoField = value;
                this.RaisePropertyChanged("xmlFirmado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("documentoError", Order=16)]
        public documentoError[] documentoError {
            get {
                return this.documentoErrorField;
            }
            set {
                this.documentoErrorField = value;
                this.RaisePropertyChanged("documentoError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.efactura.isaltda.py/")]
    public partial class resultadoRuc : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rucField;
        
        private string codigoRespuestaField;
        
        private string mensajeErrorField;
        
        private string razonSocialField;
        
        private string codigoEstadoRucField;
        
        private string descripcionEstadoRucField;
        
        private string facturadorElectronicoField;
        
        private string respuestaOriginalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ruc {
            get {
                return this.rucField;
            }
            set {
                this.rucField = value;
                this.RaisePropertyChanged("ruc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
                this.RaisePropertyChanged("codigoRespuesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string mensajeError {
            get {
                return this.mensajeErrorField;
            }
            set {
                this.mensajeErrorField = value;
                this.RaisePropertyChanged("mensajeError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string razonSocial {
            get {
                return this.razonSocialField;
            }
            set {
                this.razonSocialField = value;
                this.RaisePropertyChanged("razonSocial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string codigoEstadoRuc {
            get {
                return this.codigoEstadoRucField;
            }
            set {
                this.codigoEstadoRucField = value;
                this.RaisePropertyChanged("codigoEstadoRuc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string descripcionEstadoRuc {
            get {
                return this.descripcionEstadoRucField;
            }
            set {
                this.descripcionEstadoRucField = value;
                this.RaisePropertyChanged("descripcionEstadoRuc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string facturadorElectronico {
            get {
                return this.facturadorElectronicoField;
            }
            set {
                this.facturadorElectronicoField = value;
                this.RaisePropertyChanged("facturadorElectronico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string respuestaOriginal {
            get {
                return this.respuestaOriginalField;
            }
            set {
                this.respuestaOriginalField = value;
                this.RaisePropertyChanged("respuestaOriginal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaRucRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.efactura.isaltda.py/", Order=0)]
        public BOTONSAP.consultas.consultaRucRequest consultaRucRequest;
        
        public consultaRucRequest1() {
        }
        
        public consultaRucRequest1(BOTONSAP.consultas.consultaRucRequest consultaRucRequest) {
            this.consultaRucRequest = consultaRucRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaRucResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultaRucResponse", Namespace="http://ws.efactura.isaltda.py/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public BOTONSAP.consultas.resultadoRuc[] consultaRucResponse1;
        
        public consultaRucResponse() {
        }
        
        public consultaRucResponse(BOTONSAP.consultas.resultadoRuc[] consultaRucResponse1) {
            this.consultaRucResponse1 = consultaRucResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.efactura.isaltda.py/")]
    public partial class consultaInutilizacionRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string apikeyField;
        
        private string usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string apikey {
            get {
                return this.apikeyField;
            }
            set {
                this.apikeyField = value;
                this.RaisePropertyChanged("apikey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.efactura.isaltda.py/")]
    public partial class consultaInutilizacionResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string tipoField;
        
        private long rangoDesdeField;
        
        private bool rangoDesdeFieldSpecified;
        
        private long rangoHastaField;
        
        private bool rangoHastaFieldSpecified;
        
        private string estadoField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long rangoDesde {
            get {
                return this.rangoDesdeField;
            }
            set {
                this.rangoDesdeField = value;
                this.RaisePropertyChanged("rangoDesde");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rangoDesdeSpecified {
            get {
                return this.rangoDesdeFieldSpecified;
            }
            set {
                this.rangoDesdeFieldSpecified = value;
                this.RaisePropertyChanged("rangoDesdeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long rangoHasta {
            get {
                return this.rangoHastaField;
            }
            set {
                this.rangoHastaField = value;
                this.RaisePropertyChanged("rangoHasta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rangoHastaSpecified {
            get {
                return this.rangoHastaFieldSpecified;
            }
            set {
                this.rangoHastaFieldSpecified = value;
                this.RaisePropertyChanged("rangoHastaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaInutilizacionRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.efactura.isaltda.py/", Order=0)]
        public BOTONSAP.consultas.consultaInutilizacionRequest consultaInutilizacionRequest;
        
        public consultaInutilizacionRequest1() {
        }
        
        public consultaInutilizacionRequest1(BOTONSAP.consultas.consultaInutilizacionRequest consultaInutilizacionRequest) {
            this.consultaInutilizacionRequest = consultaInutilizacionRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaInutilizacionResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.efactura.isaltda.py/", Order=0)]
        public BOTONSAP.consultas.consultaInutilizacionResponse consultaInutilizacionResponse;
        
        public consultaInutilizacionResponse1() {
        }
        
        public consultaInutilizacionResponse1(BOTONSAP.consultas.consultaInutilizacionResponse consultaInutilizacionResponse) {
            this.consultaInutilizacionResponse = consultaInutilizacionResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.efactura.isaltda.py/")]
    public partial class consultaDEPorCicloRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cicloField;
        
        private estadoDocumento estadoDocumentoField;
        
        private bool estadoDocumentoFieldSpecified;
        
        private string tipoDocumentoField;
        
        private string paginaField;
        
        private string cantidadField;
        
        private string apikeyField;
        
        private string usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ciclo {
            get {
                return this.cicloField;
            }
            set {
                this.cicloField = value;
                this.RaisePropertyChanged("ciclo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public estadoDocumento estadoDocumento {
            get {
                return this.estadoDocumentoField;
            }
            set {
                this.estadoDocumentoField = value;
                this.RaisePropertyChanged("estadoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoDocumentoSpecified {
            get {
                return this.estadoDocumentoFieldSpecified;
            }
            set {
                this.estadoDocumentoFieldSpecified = value;
                this.RaisePropertyChanged("estadoDocumentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=2)]
        public string tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("tipoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=3)]
        public string pagina {
            get {
                return this.paginaField;
            }
            set {
                this.paginaField = value;
                this.RaisePropertyChanged("pagina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=4)]
        public string cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string apikey {
            get {
                return this.apikeyField;
            }
            set {
                this.apikeyField = value;
                this.RaisePropertyChanged("apikey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.efactura.isaltda.py/")]
    public enum estadoDocumento {
        
        /// <remarks/>
        INGRESADO,
        
        /// <remarks/>
        APROBADO,
        
        /// <remarks/>
        APROBADO_OBS,
        
        /// <remarks/>
        RECHAZADO,
        
        /// <remarks/>
        CANCELADO,
        
        /// <remarks/>
        INUTILIZADO,
        
        /// <remarks/>
        REINGRESADO,
        
        /// <remarks/>
        RECHAZADO_REINGRESADO,
        
        /// <remarks/>
        RECHAZADO_INUTILIZADO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.efactura.isaltda.py/")]
    public partial class consultaDEPorCicloResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private documento[] documentosField;
        
        private totales totalesField;
        
        private datosPaginacion datosPaginacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public documento[] documentos {
            get {
                return this.documentosField;
            }
            set {
                this.documentosField = value;
                this.RaisePropertyChanged("documentos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public totales totales {
            get {
                return this.totalesField;
            }
            set {
                this.totalesField = value;
                this.RaisePropertyChanged("totales");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public datosPaginacion datosPaginacion {
            get {
                return this.datosPaginacionField;
            }
            set {
                this.datosPaginacionField = value;
                this.RaisePropertyChanged("datosPaginacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaDEPorCicloRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.efactura.isaltda.py/", Order=0)]
        public BOTONSAP.consultas.consultaDEPorCicloRequest consultaDEPorCicloRequest;
        
        public consultaDEPorCicloRequest1() {
        }
        
        public consultaDEPorCicloRequest1(BOTONSAP.consultas.consultaDEPorCicloRequest consultaDEPorCicloRequest) {
            this.consultaDEPorCicloRequest = consultaDEPorCicloRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaDEPorCicloResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.efactura.isaltda.py/", Order=0)]
        public BOTONSAP.consultas.consultaDEPorCicloResponse consultaDEPorCicloResponse;
        
        public consultaDEPorCicloResponse1() {
        }
        
        public consultaDEPorCicloResponse1(BOTONSAP.consultas.consultaDEPorCicloResponse consultaDEPorCicloResponse) {
            this.consultaDEPorCicloResponse = consultaDEPorCicloResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.efactura.isaltda.py/")]
    public partial class consultaPorCDCRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cdcField;
        
        private bool retornarKuDEField;
        
        private bool retornarKuDEFieldSpecified;
        
        private string nombrePlantillaField;
        
        private bool retornarRespuestaOriginalField;
        
        private bool retornarRespuestaOriginalFieldSpecified;
        
        private bool retornarXmlDEField;
        
        private bool retornarXmlDEFieldSpecified;
        
        private string apikeyField;
        
        private string usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string cdc {
            get {
                return this.cdcField;
            }
            set {
                this.cdcField = value;
                this.RaisePropertyChanged("cdc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool retornarKuDE {
            get {
                return this.retornarKuDEField;
            }
            set {
                this.retornarKuDEField = value;
                this.RaisePropertyChanged("retornarKuDE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool retornarKuDESpecified {
            get {
                return this.retornarKuDEFieldSpecified;
            }
            set {
                this.retornarKuDEFieldSpecified = value;
                this.RaisePropertyChanged("retornarKuDESpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string nombrePlantilla {
            get {
                return this.nombrePlantillaField;
            }
            set {
                this.nombrePlantillaField = value;
                this.RaisePropertyChanged("nombrePlantilla");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool retornarRespuestaOriginal {
            get {
                return this.retornarRespuestaOriginalField;
            }
            set {
                this.retornarRespuestaOriginalField = value;
                this.RaisePropertyChanged("retornarRespuestaOriginal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool retornarRespuestaOriginalSpecified {
            get {
                return this.retornarRespuestaOriginalFieldSpecified;
            }
            set {
                this.retornarRespuestaOriginalFieldSpecified = value;
                this.RaisePropertyChanged("retornarRespuestaOriginalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool retornarXmlDE {
            get {
                return this.retornarXmlDEField;
            }
            set {
                this.retornarXmlDEField = value;
                this.RaisePropertyChanged("retornarXmlDE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool retornarXmlDESpecified {
            get {
                return this.retornarXmlDEFieldSpecified;
            }
            set {
                this.retornarXmlDEFieldSpecified = value;
                this.RaisePropertyChanged("retornarXmlDESpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string apikey {
            get {
                return this.apikeyField;
            }
            set {
                this.apikeyField = value;
                this.RaisePropertyChanged("apikey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.efactura.isaltda.py/")]
    public partial class consultaPorCDCResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoRespuestaField;
        
        private string mensajeRespuestaField;
        
        private byte[] kudeField;
        
        private string respuestaOriginalField;
        
        private string xmlDEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
                this.RaisePropertyChanged("codigoRespuesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string mensajeRespuesta {
            get {
                return this.mensajeRespuestaField;
            }
            set {
                this.mensajeRespuestaField = value;
                this.RaisePropertyChanged("mensajeRespuesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] kude {
            get {
                return this.kudeField;
            }
            set {
                this.kudeField = value;
                this.RaisePropertyChanged("kude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string respuestaOriginal {
            get {
                return this.respuestaOriginalField;
            }
            set {
                this.respuestaOriginalField = value;
                this.RaisePropertyChanged("respuestaOriginal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string xmlDE {
            get {
                return this.xmlDEField;
            }
            set {
                this.xmlDEField = value;
                this.RaisePropertyChanged("xmlDE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaPorCDCRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.efactura.isaltda.py/", Order=0)]
        public BOTONSAP.consultas.consultaPorCDCRequest consultaPorCDCRequest;
        
        public consultaPorCDCRequest1() {
        }
        
        public consultaPorCDCRequest1(BOTONSAP.consultas.consultaPorCDCRequest consultaPorCDCRequest) {
            this.consultaPorCDCRequest = consultaPorCDCRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaPorCDCResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.efactura.isaltda.py/", Order=0)]
        public BOTONSAP.consultas.consultaPorCDCResponse consultaPorCDCResponse;
        
        public consultaPorCDCResponse1() {
        }
        
        public consultaPorCDCResponse1(BOTONSAP.consultas.consultaPorCDCResponse consultaPorCDCResponse) {
            this.consultaPorCDCResponse = consultaPorCDCResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.efactura.isaltda.py/")]
    public partial class consultaRecibidoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cdcField;
        
        private string apikeyField;
        
        private string usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string cdc {
            get {
                return this.cdcField;
            }
            set {
                this.cdcField = value;
                this.RaisePropertyChanged("cdc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string apikey {
            get {
                return this.apikeyField;
            }
            set {
                this.apikeyField = value;
                this.RaisePropertyChanged("apikey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.efactura.isaltda.py/")]
    public partial class consultaRecibidoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] documentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
                this.RaisePropertyChanged("documento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaRecibidoRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.efactura.isaltda.py/", Order=0)]
        public BOTONSAP.consultas.consultaRecibidoRequest consultaRecibidoRequest;
        
        public consultaRecibidoRequest1() {
        }
        
        public consultaRecibidoRequest1(BOTONSAP.consultas.consultaRecibidoRequest consultaRecibidoRequest) {
            this.consultaRecibidoRequest = consultaRecibidoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaRecibidoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.efactura.isaltda.py/", Order=0)]
        public BOTONSAP.consultas.consultaRecibidoResponse consultaRecibidoResponse;
        
        public consultaRecibidoResponse1() {
        }
        
        public consultaRecibidoResponse1(BOTONSAP.consultas.consultaRecibidoResponse consultaRecibidoResponse) {
            this.consultaRecibidoResponse = consultaRecibidoResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.efactura.isaltda.py/")]
    public partial class consultaRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long[] idField;
        
        private string[] cdcField;
        
        private numeroTipoDocumento[] numeroTipoDocumentoField;
        
        private System.DateTime fechaEmisionDesdeField;
        
        private bool fechaEmisionDesdeFieldSpecified;
        
        private System.DateTime fechaEmisionHastaField;
        
        private bool fechaEmisionHastaFieldSpecified;
        
        private System.DateTime fechaIngresoDesdeField;
        
        private bool fechaIngresoDesdeFieldSpecified;
        
        private System.DateTime fechaIngresoHastaField;
        
        private bool fechaIngresoHastaFieldSpecified;
        
        private string maximoResultadosField;
        
        private string resultadoInicialField;
        
        private bool retornarKuDEField;
        
        private bool retornarKuDEFieldSpecified;
        
        private long timbradoField;
        
        private bool timbradoFieldSpecified;
        
        private bool retornarXmlFirmadoField;
        
        private bool retornarXmlFirmadoFieldSpecified;
        
        private string establecimientoField;
        
        private string puntoExpedicionField;
        
        private string naturalezaReceptorField;
        
        private long numeroDocumentoField;
        
        private bool numeroDocumentoFieldSpecified;
        
        private long rucField;
        
        private bool rucFieldSpecified;
        
        private string dvField;
        
        private string apikeyField;
        
        private string usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("id", Order=0)]
        public long[] id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cdc", Order=1)]
        public string[] cdc {
            get {
                return this.cdcField;
            }
            set {
                this.cdcField = value;
                this.RaisePropertyChanged("cdc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("numeroTipoDocumento", Order=2)]
        public numeroTipoDocumento[] numeroTipoDocumento {
            get {
                return this.numeroTipoDocumentoField;
            }
            set {
                this.numeroTipoDocumentoField = value;
                this.RaisePropertyChanged("numeroTipoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime fechaEmisionDesde {
            get {
                return this.fechaEmisionDesdeField;
            }
            set {
                this.fechaEmisionDesdeField = value;
                this.RaisePropertyChanged("fechaEmisionDesde");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaEmisionDesdeSpecified {
            get {
                return this.fechaEmisionDesdeFieldSpecified;
            }
            set {
                this.fechaEmisionDesdeFieldSpecified = value;
                this.RaisePropertyChanged("fechaEmisionDesdeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime fechaEmisionHasta {
            get {
                return this.fechaEmisionHastaField;
            }
            set {
                this.fechaEmisionHastaField = value;
                this.RaisePropertyChanged("fechaEmisionHasta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaEmisionHastaSpecified {
            get {
                return this.fechaEmisionHastaFieldSpecified;
            }
            set {
                this.fechaEmisionHastaFieldSpecified = value;
                this.RaisePropertyChanged("fechaEmisionHastaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime fechaIngresoDesde {
            get {
                return this.fechaIngresoDesdeField;
            }
            set {
                this.fechaIngresoDesdeField = value;
                this.RaisePropertyChanged("fechaIngresoDesde");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaIngresoDesdeSpecified {
            get {
                return this.fechaIngresoDesdeFieldSpecified;
            }
            set {
                this.fechaIngresoDesdeFieldSpecified = value;
                this.RaisePropertyChanged("fechaIngresoDesdeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime fechaIngresoHasta {
            get {
                return this.fechaIngresoHastaField;
            }
            set {
                this.fechaIngresoHastaField = value;
                this.RaisePropertyChanged("fechaIngresoHasta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaIngresoHastaSpecified {
            get {
                return this.fechaIngresoHastaFieldSpecified;
            }
            set {
                this.fechaIngresoHastaFieldSpecified = value;
                this.RaisePropertyChanged("fechaIngresoHastaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=7)]
        public string maximoResultados {
            get {
                return this.maximoResultadosField;
            }
            set {
                this.maximoResultadosField = value;
                this.RaisePropertyChanged("maximoResultados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=8)]
        public string resultadoInicial {
            get {
                return this.resultadoInicialField;
            }
            set {
                this.resultadoInicialField = value;
                this.RaisePropertyChanged("resultadoInicial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool retornarKuDE {
            get {
                return this.retornarKuDEField;
            }
            set {
                this.retornarKuDEField = value;
                this.RaisePropertyChanged("retornarKuDE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool retornarKuDESpecified {
            get {
                return this.retornarKuDEFieldSpecified;
            }
            set {
                this.retornarKuDEFieldSpecified = value;
                this.RaisePropertyChanged("retornarKuDESpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public long timbrado {
            get {
                return this.timbradoField;
            }
            set {
                this.timbradoField = value;
                this.RaisePropertyChanged("timbrado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timbradoSpecified {
            get {
                return this.timbradoFieldSpecified;
            }
            set {
                this.timbradoFieldSpecified = value;
                this.RaisePropertyChanged("timbradoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool retornarXmlFirmado {
            get {
                return this.retornarXmlFirmadoField;
            }
            set {
                this.retornarXmlFirmadoField = value;
                this.RaisePropertyChanged("retornarXmlFirmado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool retornarXmlFirmadoSpecified {
            get {
                return this.retornarXmlFirmadoFieldSpecified;
            }
            set {
                this.retornarXmlFirmadoFieldSpecified = value;
                this.RaisePropertyChanged("retornarXmlFirmadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=12)]
        public string establecimiento {
            get {
                return this.establecimientoField;
            }
            set {
                this.establecimientoField = value;
                this.RaisePropertyChanged("establecimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=13)]
        public string puntoExpedicion {
            get {
                return this.puntoExpedicionField;
            }
            set {
                this.puntoExpedicionField = value;
                this.RaisePropertyChanged("puntoExpedicion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=14)]
        public string naturalezaReceptor {
            get {
                return this.naturalezaReceptorField;
            }
            set {
                this.naturalezaReceptorField = value;
                this.RaisePropertyChanged("naturalezaReceptor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public long numeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                this.numeroDocumentoField = value;
                this.RaisePropertyChanged("numeroDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroDocumentoSpecified {
            get {
                return this.numeroDocumentoFieldSpecified;
            }
            set {
                this.numeroDocumentoFieldSpecified = value;
                this.RaisePropertyChanged("numeroDocumentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public long ruc {
            get {
                return this.rucField;
            }
            set {
                this.rucField = value;
                this.RaisePropertyChanged("ruc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rucSpecified {
            get {
                return this.rucFieldSpecified;
            }
            set {
                this.rucFieldSpecified = value;
                this.RaisePropertyChanged("rucSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=17)]
        public string dv {
            get {
                return this.dvField;
            }
            set {
                this.dvField = value;
                this.RaisePropertyChanged("dv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string apikey {
            get {
                return this.apikeyField;
            }
            set {
                this.apikeyField = value;
                this.RaisePropertyChanged("apikey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.efactura.isaltda.py/")]
    public partial class consultaResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cantidadResultadosField;
        
        private string cantidadTotalResultadosField;
        
        private documento[] documentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string cantidadResultados {
            get {
                return this.cantidadResultadosField;
            }
            set {
                this.cantidadResultadosField = value;
                this.RaisePropertyChanged("cantidadResultados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string cantidadTotalResultados {
            get {
                return this.cantidadTotalResultadosField;
            }
            set {
                this.cantidadTotalResultadosField = value;
                this.RaisePropertyChanged("cantidadTotalResultados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("documento", Order=2)]
        public documento[] documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
                this.RaisePropertyChanged("documento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.efactura.isaltda.py/", Order=0)]
        public BOTONSAP.consultas.consultaRequest consultaRequest;
        
        public consultaRequest1() {
        }
        
        public consultaRequest1(BOTONSAP.consultas.consultaRequest consultaRequest) {
            this.consultaRequest = consultaRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.efactura.isaltda.py/", Order=0)]
        public BOTONSAP.consultas.consultaResponse consultaResponse;
        
        public consultaResponse1() {
        }
        
        public consultaResponse1(BOTONSAP.consultas.consultaResponse consultaResponse) {
            this.consultaResponse = consultaResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConsultasChannel : BOTONSAP.consultas.Consultas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultasClient : System.ServiceModel.ClientBase<BOTONSAP.consultas.Consultas>, BOTONSAP.consultas.Consultas {
        
        public ConsultasClient() {
        }
        
        public ConsultasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BOTONSAP.consultas.consultaRucResponse BOTONSAP.consultas.Consultas.consultaRuc(BOTONSAP.consultas.consultaRucRequest1 request) {
            return base.Channel.consultaRuc(request);
        }
        
        public BOTONSAP.consultas.resultadoRuc[] consultaRuc(BOTONSAP.consultas.consultaRucRequest consultaRucRequest) {
            BOTONSAP.consultas.consultaRucRequest1 inValue = new BOTONSAP.consultas.consultaRucRequest1();
            inValue.consultaRucRequest = consultaRucRequest;
            BOTONSAP.consultas.consultaRucResponse retVal = ((BOTONSAP.consultas.Consultas)(this)).consultaRuc(inValue);
            return retVal.consultaRucResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BOTONSAP.consultas.consultaRucResponse> BOTONSAP.consultas.Consultas.consultaRucAsync(BOTONSAP.consultas.consultaRucRequest1 request) {
            return base.Channel.consultaRucAsync(request);
        }
        
        public System.Threading.Tasks.Task<BOTONSAP.consultas.consultaRucResponse> consultaRucAsync(BOTONSAP.consultas.consultaRucRequest consultaRucRequest) {
            BOTONSAP.consultas.consultaRucRequest1 inValue = new BOTONSAP.consultas.consultaRucRequest1();
            inValue.consultaRucRequest = consultaRucRequest;
            return ((BOTONSAP.consultas.Consultas)(this)).consultaRucAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BOTONSAP.consultas.consultaInutilizacionResponse1 BOTONSAP.consultas.Consultas.consultaInutilizacion(BOTONSAP.consultas.consultaInutilizacionRequest1 request) {
            return base.Channel.consultaInutilizacion(request);
        }
        
        public BOTONSAP.consultas.consultaInutilizacionResponse consultaInutilizacion(BOTONSAP.consultas.consultaInutilizacionRequest consultaInutilizacionRequest) {
            BOTONSAP.consultas.consultaInutilizacionRequest1 inValue = new BOTONSAP.consultas.consultaInutilizacionRequest1();
            inValue.consultaInutilizacionRequest = consultaInutilizacionRequest;
            BOTONSAP.consultas.consultaInutilizacionResponse1 retVal = ((BOTONSAP.consultas.Consultas)(this)).consultaInutilizacion(inValue);
            return retVal.consultaInutilizacionResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BOTONSAP.consultas.consultaInutilizacionResponse1> BOTONSAP.consultas.Consultas.consultaInutilizacionAsync(BOTONSAP.consultas.consultaInutilizacionRequest1 request) {
            return base.Channel.consultaInutilizacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<BOTONSAP.consultas.consultaInutilizacionResponse1> consultaInutilizacionAsync(BOTONSAP.consultas.consultaInutilizacionRequest consultaInutilizacionRequest) {
            BOTONSAP.consultas.consultaInutilizacionRequest1 inValue = new BOTONSAP.consultas.consultaInutilizacionRequest1();
            inValue.consultaInutilizacionRequest = consultaInutilizacionRequest;
            return ((BOTONSAP.consultas.Consultas)(this)).consultaInutilizacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BOTONSAP.consultas.consultaDEPorCicloResponse1 BOTONSAP.consultas.Consultas.consultaDEPorCiclo(BOTONSAP.consultas.consultaDEPorCicloRequest1 request) {
            return base.Channel.consultaDEPorCiclo(request);
        }
        
        public BOTONSAP.consultas.consultaDEPorCicloResponse consultaDEPorCiclo(BOTONSAP.consultas.consultaDEPorCicloRequest consultaDEPorCicloRequest) {
            BOTONSAP.consultas.consultaDEPorCicloRequest1 inValue = new BOTONSAP.consultas.consultaDEPorCicloRequest1();
            inValue.consultaDEPorCicloRequest = consultaDEPorCicloRequest;
            BOTONSAP.consultas.consultaDEPorCicloResponse1 retVal = ((BOTONSAP.consultas.Consultas)(this)).consultaDEPorCiclo(inValue);
            return retVal.consultaDEPorCicloResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BOTONSAP.consultas.consultaDEPorCicloResponse1> BOTONSAP.consultas.Consultas.consultaDEPorCicloAsync(BOTONSAP.consultas.consultaDEPorCicloRequest1 request) {
            return base.Channel.consultaDEPorCicloAsync(request);
        }
        
        public System.Threading.Tasks.Task<BOTONSAP.consultas.consultaDEPorCicloResponse1> consultaDEPorCicloAsync(BOTONSAP.consultas.consultaDEPorCicloRequest consultaDEPorCicloRequest) {
            BOTONSAP.consultas.consultaDEPorCicloRequest1 inValue = new BOTONSAP.consultas.consultaDEPorCicloRequest1();
            inValue.consultaDEPorCicloRequest = consultaDEPorCicloRequest;
            return ((BOTONSAP.consultas.Consultas)(this)).consultaDEPorCicloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BOTONSAP.consultas.consultaPorCDCResponse1 BOTONSAP.consultas.Consultas.consultaPorCDC(BOTONSAP.consultas.consultaPorCDCRequest1 request) {
            return base.Channel.consultaPorCDC(request);
        }
        
        public BOTONSAP.consultas.consultaPorCDCResponse consultaPorCDC(BOTONSAP.consultas.consultaPorCDCRequest consultaPorCDCRequest) {
            BOTONSAP.consultas.consultaPorCDCRequest1 inValue = new BOTONSAP.consultas.consultaPorCDCRequest1();
            inValue.consultaPorCDCRequest = consultaPorCDCRequest;
            BOTONSAP.consultas.consultaPorCDCResponse1 retVal = ((BOTONSAP.consultas.Consultas)(this)).consultaPorCDC(inValue);
            return retVal.consultaPorCDCResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BOTONSAP.consultas.consultaPorCDCResponse1> BOTONSAP.consultas.Consultas.consultaPorCDCAsync(BOTONSAP.consultas.consultaPorCDCRequest1 request) {
            return base.Channel.consultaPorCDCAsync(request);
        }
        
        public System.Threading.Tasks.Task<BOTONSAP.consultas.consultaPorCDCResponse1> consultaPorCDCAsync(BOTONSAP.consultas.consultaPorCDCRequest consultaPorCDCRequest) {
            BOTONSAP.consultas.consultaPorCDCRequest1 inValue = new BOTONSAP.consultas.consultaPorCDCRequest1();
            inValue.consultaPorCDCRequest = consultaPorCDCRequest;
            return ((BOTONSAP.consultas.Consultas)(this)).consultaPorCDCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BOTONSAP.consultas.consultaRecibidoResponse1 BOTONSAP.consultas.Consultas.consultaRecibido(BOTONSAP.consultas.consultaRecibidoRequest1 request) {
            return base.Channel.consultaRecibido(request);
        }
        
        public BOTONSAP.consultas.consultaRecibidoResponse consultaRecibido(BOTONSAP.consultas.consultaRecibidoRequest consultaRecibidoRequest) {
            BOTONSAP.consultas.consultaRecibidoRequest1 inValue = new BOTONSAP.consultas.consultaRecibidoRequest1();
            inValue.consultaRecibidoRequest = consultaRecibidoRequest;
            BOTONSAP.consultas.consultaRecibidoResponse1 retVal = ((BOTONSAP.consultas.Consultas)(this)).consultaRecibido(inValue);
            return retVal.consultaRecibidoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BOTONSAP.consultas.consultaRecibidoResponse1> BOTONSAP.consultas.Consultas.consultaRecibidoAsync(BOTONSAP.consultas.consultaRecibidoRequest1 request) {
            return base.Channel.consultaRecibidoAsync(request);
        }
        
        public System.Threading.Tasks.Task<BOTONSAP.consultas.consultaRecibidoResponse1> consultaRecibidoAsync(BOTONSAP.consultas.consultaRecibidoRequest consultaRecibidoRequest) {
            BOTONSAP.consultas.consultaRecibidoRequest1 inValue = new BOTONSAP.consultas.consultaRecibidoRequest1();
            inValue.consultaRecibidoRequest = consultaRecibidoRequest;
            return ((BOTONSAP.consultas.Consultas)(this)).consultaRecibidoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BOTONSAP.consultas.consultaResponse1 BOTONSAP.consultas.Consultas.consulta(BOTONSAP.consultas.consultaRequest1 request) {
            return base.Channel.consulta(request);
        }
        
        public BOTONSAP.consultas.consultaResponse consulta(BOTONSAP.consultas.consultaRequest consultaRequest) {
            BOTONSAP.consultas.consultaRequest1 inValue = new BOTONSAP.consultas.consultaRequest1();
            inValue.consultaRequest = consultaRequest;
            BOTONSAP.consultas.consultaResponse1 retVal = ((BOTONSAP.consultas.Consultas)(this)).consulta(inValue);
            return retVal.consultaResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BOTONSAP.consultas.consultaResponse1> BOTONSAP.consultas.Consultas.consultaAsync(BOTONSAP.consultas.consultaRequest1 request) {
            return base.Channel.consultaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BOTONSAP.consultas.consultaResponse1> consultaAsync(BOTONSAP.consultas.consultaRequest consultaRequest) {
            BOTONSAP.consultas.consultaRequest1 inValue = new BOTONSAP.consultas.consultaRequest1();
            inValue.consultaRequest = consultaRequest;
            return ((BOTONSAP.consultas.Consultas)(this)).consultaAsync(inValue);
        }
    }
}
